const weatherNames: { [key: string]: string } = {
  clearsky_day: 'Clear sky',
  clearsky_night: 'Clear sky',
  fair_day: 'Fair',
  fair_night: 'Fair',
  partlycloudy_day: 'Partly cloudy',
  partlycloudy_night: 'Partly cloudy',
  cloudy: 'Cloudy',
  lightrainshowers_day: 'Light rain showers',
  lightrainshowers_night: 'Light rain showers',
  rainshowers_day: 'Rain showers',
  rainshowers_night: 'Rain showers',
  heavyrainshowers_day: 'Heavy rain showers',
  heavyrainshowers_night: 'Heavy rain showers',
  lightrainshowersandthunder_day: 'Light rain showers and thunder',
  lightrainshowersandthunder_night: 'Light rain showers and thunder',
  rainshowersandthunder_day: 'Rain showers and thunder',
  rainshowersandthunder_night: 'Rain showers and thunder',
  heavyrainshowersandthunder_day: 'Heavy rain showers and thunder',
  heavyrainshowersandthunder_night: 'Heavy rain showers and thunder',
  lightsleetshowers_day: 'Light sleet showers',
  lightsleetshowers_night: 'Light sleet showers',
  sleetshowers_day: 'Sleet showers',
  sleetshowers_night: 'Sleet showers',
  heavysleetshowers_day: 'Heavy sleet showers',
  heavysleetshowers_night: 'Heavy sleet showers',
  lightssleetshowersandthunder_day: 'Light sleet showers and thunder',
  lightssleetshowersandthunder_night: 'Light sleet showers and thunder',
  sleetshowersandthunder_day: 'Sleet showers and thunder',
  sleetshowersandthunder_night: 'Sleet showers and thunder',
  heavysleetshowersandthunder_day: 'Heavy sleet showers and thunder',
  heavysleetshowersandthunder_night: 'Heavy sleet showers and thunder',
  lightsnowshowers_day: 'Light snow showers',
  lightsnowshowers_night: 'Light snow showers',
  snowshowers_day: 'Snow showers',
  snowshowers_night: 'Snow showers',
  heavysnowshowers_day: 'Heavy snow showers',
  heavysnowshowers_night: 'Heavy snow showers',
  lightssnowshowersandthunder_day: 'Light snow showers and thunder',
  lightssnowshowersandthunder_night: 'Light snow showers and thunder',
  snowshowersandthunder_day: 'Snow showers and thunder',
  snowshowersandthunder_night: 'Snow showers and thunder',
  heavysnowshowersandthunder_day: 'Heavy snow showers and thunder',
  heavysnowshowersandthunder_night: 'Heavy snow showers and thunder',
  lightrain: 'Light rain',
  lightrain_night: 'Light rain',
  rain_day: 'Rain',
  rain_night: 'Rain',
  heavyrain_day: 'Heavy rain',
  heavyrain_night: 'Heavy rain',
  lightrainandthunder_day: 'Light rain and thunder',
  lightrainandthunder_night: 'Light rain and thunder',
  rainandthunder_day: 'Rain and thunder',
  rainandthunder_night: 'Rain and thunder',
  heavyrainandthunder_day: 'Heavy rain and thunder',
  heavyrainandthunder_night: 'Heavy rain and thunder',
  lightsleet_day: 'Light sleet',
  lightsleet_night: 'Light sleet',
  sleet_day: 'Sleet',
  sleet_night: 'Sleet',
  heavysleet_day: 'Heavy sleet',
  heavysleet_night: 'Heavy sleet',
  lightsleetandthunder_day: 'Light sleet and thunder',
  lightsleetandthunder_night: 'Light sleet and thunder',
  sleetandthunder_day: 'Sleet and thunder',
  sleetandthunder_night: 'Sleet and thunder',
  heavysleetandthunder_day: 'Heavy sleet and thunder',
  heavysleetandthunder_night: 'Heavy sleet and thunder',
  lightsnow_day: 'Light snow',
  lightsnow_night: 'Light snow',
  snow_day: 'Snow',
  snow_night: 'Snow',
  heavysnow_day: 'Heavy snow',
  heavysnow_night: 'Heavy snow',
  lightsnowandthunder_day: 'Light snow and thunder',
  lightsnowandthunder_night: 'Light snow and thunder',
  snowandthunder_day: 'Snow and thunder',
  snowandthunder_night: 'Snow and thunder',
  heavysnowandthunder_day: 'Heavy snow and thunder',
  heavysnowandthunder_night: 'Heavy snow and thunder',
  fog_night: 'Fog',
  fog_day: 'Fog',
};

export default weatherNames;